Repository SLTDV/Choice-iOS, pull requests merged in 2023-04, with the labels that each got.

#54 게시물 이미지 UI 변경
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#55 UserSecurityInfoVC SignUpButton 상태 제어 / 회원가입 UI 수정
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Sources/Present/Auth/SignUp/UserSecurityInfo/ViewController/UserSecurityInfoViewController.swift
  Sources/Util/Class/UnderLineTextField.swift
Labels: 3️⃣Priority: Low

#56 Xcode 14.3에 따른 KingFisher Version Upgrade
  .package.resolved
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 🐛 Bugfix, 2️⃣Priority: Medium

#57 댓글 삭제 기능 구현
  Project.swift
  Sources/Network/APIConstants.swift
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/Model/CommentModel.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
  Sources/Util/Class/LoadingIndicator.swift
Labels: 1️⃣Priority: High, ✨ Feature

#58 [Refactoring] APIConstants
  Sources/Network/APIConstants.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#59 댓글 - 작성자 프로필 이미지 적용
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/Model/CommentModel.swift
Labels: 1️⃣Priority: High, ✨ Feature

#61 프로필 이미지 업로드 로직 변경
  Sources/Network/APIConstants.swift
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewModel/UserProfileInfoViewModel.swift
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/Model/CommentModel.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Profile/Model/ProfileModel.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 🚑 Hotfix, 🛠️Refactoring

#62 addPost 조건 수정
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#64 앱 아이콘 적용
  Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Resources/Assets.xcassets/AppIcon.appiconset/172.png
  Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Resources/Assets.xcassets/AppIcon.appiconset/196.png
  Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Resources/Assets.xcassets/AppIcon.appiconset/216.png
  Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Resources/Assets.xcassets/AppIcon.appiconset/48.png
  Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Resources/Assets.xcassets/AppIcon.appiconset/55.png
  Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Resources/Assets.xcassets/AppIcon.appiconset/64.png
  Resources/Assets.xcassets/AppIcon.appiconset/66.png
  Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Resources/Assets.xcassets/AppIcon.appiconset/88.png
  Resources/Assets.xcassets/AppIcon.appiconset/92.png
  Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Sources/Network/KeyChain.swift
Labels: ✨ Feature

#65 descriptionLabel 수정
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 🐛 Bugfix, 3️⃣Priority: Low

#66 투표 버튼 애니메이션 추가
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Util/Extension/UIView/UIView.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#68 투표 시 reload 문제 해결
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Common/Model/PostModel.swift
  Sources/Present/Common/Model/VoteModel.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Util/Extension/UIView/UIView.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring

#69 게시물 정렬 관련
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring, ✨ Feature

#70 Splash 화면 생성
  Resources/LaunchScreen.storyboard
Labels: 3️⃣Priority: Low, ✨ Feature

#73 :bug: Fix 회원가입 시도 중 이미지 업로드 문제
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewModel/UserProfileInfoViewModel.swift
Labels: 🚑 Hotfix, 🐛 Bugfix

#74 [Fix] 게시물 삭제 버튼 보이지 않던 문제
  Sources/Network/APIConstants.swift
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 🐛 Bugfix, 3️⃣Priority: Low

#75 Detail 페이지 버튼, VoteOptionLabel 수정
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 3️⃣Priority: Low

#76 메인 게시물 pagination 적용
  Sources/App/Coordinator/Main/Home/HomeCoordinator.swift
  Sources/App/Coordinator/Main/Post/DetailPostCoordinator.swift
  Sources/App/Step/ChoiceStep.swift
  Sources/Network/APIConstants.swift
  Sources/Network/JwtRequestInterceptor.swift
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Common/Model/PostModel.swift
  Sources/Present/Common/Model/PostRequest.swift
  Sources/Present/Detail/Model/CommentModel.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Present/Main/Profile/Model/ProfileModel.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#77 Main - Pull to Refresh 기능 구현
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#78 프로필 페이지에 내 게시물 Layout 수정
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 🐛 Bugfix, 2️⃣Priority: Medium

#79 댓글 pagination 적용
  Sources/Present/Detail/Model/CommentModel.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Util/Extension/ViewController/UIViewController.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#80 hotfix/comment pagination
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 🚑 Hotfix

#82 Refactor/Interceptor
  Sources/App/Coordinator/App/AppCoordinator.swift
  Sources/Network/JwtRequestInterceptor.swift
  Sources/Network/KeyChain.swift
  Sources/Network/KeyChain/KeyChain.swift
  Sources/Network/KeyChain/KeyChainService.swift
  Sources/Network/ManageTokenModel.swift
  Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
  Sources/Present/Auth/SignIn/ViewModel/SignInViewModel.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Util/Extension/String/StringToDate.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring
