Repository SLTDV/Choice-iOS, pull requests merged in 2023-11, with the labels that each got.

#172 인스타 공유 이슈 해결
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 🐛 Bugfix, 3️⃣Priority: Low

#171 네트워크 통신 추상화
  Projects/App/Project.swift
  Projects/App/Sources/App/Application/AppDelegate.swift
  Projects/App/Sources/App/Coordinator/App/AppCoordinator.swift
  Projects/App/Sources/Present/AddPost/AddImage/ViewModel/AddImageViewModel.swift
  Projects/App/Sources/Present/Auth/SignIn/ViewModel/SignInViewModel.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/App/Sources/Present/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Present/Profile/ViewModel/ProfileViewModel.swift
  Projects/Core/DesignSystem/Sources/Util/Class/ShareToInstagram.swift
  Projects/Core/JwtStore/Sources/DIContainer.swift
  Projects/Domain/NetworkService/Project.swift
  Projects/Domain/NetworkService/Sources/HTTPHeaderField.swift
  Projects/Domain/NetworkService/Sources/TargetType.swift
  Projects/Domain/NetworkService/Tests/.gitkeep
  Projects/Domain/NetworkService/Tests/Test.swift
  Tests/.gitkeep
  Tests/Test.swift
  Tuist/ProjectDescriptionHelpers/Dependency+Target.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring

#174 네트워크 연동 추상화 적용 - FindPost, VotePost
  Projects/App/Sources/Present/Common/Model/PostModel.swift
  Projects/App/Sources/Present/Common/Model/PostRequest.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/App/Sources/Present/Home/HomeTarget.swift
  Projects/App/Sources/Present/Home/Model/AddPostModel.swift
  Projects/App/Sources/Present/Home/ViewModel/HomeViewModel.swift
  Projects/Domain/NetworkService/Tests/.gitkeep
  Tests/.gitkeep
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#175 Add CommentModel, PostList - 초기화 함수
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Common/Model/PostModel.swift
  Projects/App/Sources/Present/Detail/Model/CommentModel.swift
  Projects/App/Sources/Present/Detail/View/Cell/CommentCell.swift
  Projects/App/Sources/Present/Detail/View/DetailPostView.swift
  Projects/App/Sources/Present/Detail/View/Modal/Model/OptionData.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#176 앱 종료 함수 `NetworkMonitor` 모듈로 이전
  Projects/App/Sources/Present/Home/ViewController/HomeViewController.swift
  Projects/Core/NetworksMonitor/Sources/AppCloseHandler.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#178 showAlert함수 매개변수 기본값 설정
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Home/ViewController/HomeViewController.swift
  Projects/Core/DesignSystem/Sources/Util/Class/AlertHelper.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring
