Repository SLTDV/Choice-iOS, pull requests merged in 2023-06, with the labels that each got.

#110 [피드백 #109] nan 이슈 해결, 프로필 and 디테일 페이지 리펙토링
  Projects/App/Sources/App/Coordinator/Main/Home/HomeCoordinator.swift
  Projects/App/Sources/App/Coordinator/Main/Post/DetailPostCoordinator.swift
  Projects/App/Sources/App/Coordinator/Main/Profile/ProfileCoordinator.swift
  Projects/App/Sources/App/Step/ChoiceStep.swift
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Common/Type/ViewControllerType.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
  Projects/Shared/Sources/Util/Class/CalculateToVoteCountPercentage.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High

#111 [피드백 #106] 댓글 LoadingIndicator 설정 및 Layout 수정
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Support/Info.plist
Labels: 🐛 Bugfix, 3️⃣Priority: Low

#113 [피드백 #112] 디테일페이지에 투표 기능 추가
  Projects/App/Sources/App/Coordinator/Main/Home/HomeCoordinator.swift
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Common/Model/PostModel.swift
  Projects/App/Sources/Present/Detail/Cell/CommentCell.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#114 게시물 UI 변경
  Projects/App/Resources/Images.xcassets/CommentCountEmoji.imageset/Contents.json
  Projects/App/Resources/Images.xcassets/CommentCountEmoji.imageset/commentCountEmoji.png
  Projects/App/Resources/Images.xcassets/VoteCountEmoji.imageset/Contents.json
  Projects/App/Resources/Images.xcassets/VoteCountEmoji.imageset/voteCountEmoji.png
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
Labels: 3️⃣Priority: Low

#115 전화번호 입력 페이지 컴포넌트 분리
  Projects/App/Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPassword/Component/inputPassword.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/Component/inputPhoneNumber.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring

#116 비빌번호 입력 페이지 컴포넌트로 분리 및 리펙토링
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPassword/Component/InputPasswordComponent.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPassword/Component/inputPassword.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPassword/ViewController/RegistrationPasswordViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/Component/InputphoneNumberComponent.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring

#122 인증번호 재요청 수정
  Projects/App/Sources/Present/Auth/FindPassword/PhoneNumber/PhoneNumberAuthViewController.swift
  Projects/App/Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/Component/InputphoneNumberComponent.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High

#124 [v1.0] 디테일 투표 이슈, keyboard 이슈 해결
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Support/Info.plist
Labels: 🚑 Hotfix, 🐛 Bugfix, 🛠️Refactoring

#126 화면 세로모드 고정
  Projects/App/Sources/App/Application/AppDelegate.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#128 BaseUrl 변경
  .gitignore
  Projects/Core/JwtStore/Sources/APIConstants.swift
Labels: 🚑 Hotfix

#130 정렬버튼 타이틀 이슈 해결
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring

#131 게시물 신고 기능 구현
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/Core/JwtStore/Sources/APIConstants.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#132 Complete Lottie 추가 및 적용
  Projects/App/Resources/CompleteLottie.json
  Projects/App/Sources/App/Coordinator/Auth/SignUp/UserProfileInformation/UserProfileInfoCoordinator.swift
  Projects/App/Sources/App/Coordinator/Main/Post/AddImageCoordinator.swift
  Projects/App/Sources/App/Step/ChoiceStep.swift
  Projects/App/Sources/Present/Auth/SignIn/ViewModel/SignInViewModel.swift
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewModel/UserProfileInfoViewModel.swift
  Projects/App/Sources/Present/Main/AddPost/AddImage/ViewModel/AddImageViewModel.swift
  Projects/Shared/Project.swift
  Projects/Shared/Sources/Util/Class/CompleteViewController/CompleteViewController.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 🚑 Hotfix, ✨ Feature

#135 실행 디바이스를 iPhone 으로 고정
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring

#134 이용약관 Modal 적용
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/Modal/PrivacyPolicyModalViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/Modal/View/AgreementComponentView.swift
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Projects/Shared/Sources/Util/Extension/UIButton/UIButton.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#141 캡처 방지 기능 추가
  Projects/App/Sources/Present/Base/BaseVC.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Projects/Shared/Sources/Util/Extension/ViewController/UIViewController.swift
Labels: 2️⃣Priority: Medium, ✨ Feature
