Repository SLTDV/Choice-iOS, pull requests merged in 2023-08, with the labels that each got.

#147 [Refactoring] DetailPost
  Projects/App/Sources/Present/Detail/Cell/CommentCell.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/Shared/Sources/Util/Class/AlertHelper.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#148 [Refactor] DetailPostVM - API 호출 함수 Observable 로 변경
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/Shared/Sources/Util/Class/AlertHelper.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#150 광고 기능 추가
  Projects/App/Project.swift
  Projects/App/Sources/App/Application/AppDelegate.swift
  Projects/App/Sources/Present/AddPost/AddContents/ViewController/AddContentsViewController.swift
  Projects/App/Sources/Present/AddPost/AddContents/ViewModel/AddContentsViewModel.swift
  Projects/App/Sources/Present/AddPost/AddImage/ViewController/AddImageViewController.swift
  Projects/App/Sources/Present/AddPost/AddImage/ViewModel/AddImageViewModel.swift
  Projects/App/Sources/Present/Advertisemets/AdvertisementsControl.swift
  Projects/App/Sources/Present/Home/Model/AddPostModel.swift
  Projects/App/Sources/Present/Home/Type/MenuOptionType.swift
  Projects/App/Sources/Present/Home/ViewController/HomeViewController.swift
  Projects/App/Sources/Present/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Present/Home/ViewModel/Support/Info.plist
  Projects/App/Sources/Present/Profile/Model/ProfileImageModel.swift
  Projects/App/Sources/Present/Profile/Model/ProfileModel.swift
  Projects/App/Sources/Present/Profile/Type/OptionItemType.swift
  Projects/App/Sources/Present/Profile/ViewController/ProfileViewController.swift
  Projects/App/Sources/Present/Profile/ViewModel/ProfileViewModel.swift
  Projects/App/Support/Info.plist
  Projects/Core/NetworksMonitor/Tests/Tests 2.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 1️⃣Priority: High, ✨ Feature

#151 HomeVC alert 수정
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Home/ViewController/HomeViewController.swift
  Projects/Shared/Sources/Util/Class/AlertHelper.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring
