Repository SLTDV/Choice-iOS, pull requests merged in 2023-09, with the labels that each got.

#152 Detail menu 부분 halfModal UI 제작
  Projects/App/Resources/Images.xcassets/InstarIcon.imageset/Contents.json
  Projects/App/Resources/Images.xcassets/InstarIcon.imageset/instargramIcon.svg
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/Modal/Model/OptionData.swift
  Projects/App/Sources/Present/Detail/ViewController/Modal/VC/DetailOptionModalViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/Modal/VC/View/Cell/DetailOptionTableViewCell.swift
Labels: 2️⃣Priority: Medium

#153 [Refactoring] PostCell
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#156 DetailVC 문제 해결
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/Shared/Sources/Util/Class/Downsampling.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring

#157 OptionModal과 alert 연결
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/Modal/VC/DetailOptionModalViewController.swift
Labels: 2️⃣Priority: Medium

#155 푸시 알림 기능 구현 (APNs + FCM)
  .gitignore
  Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/App/Resources/Choice.entitlements
  Projects/App/Sources/App/Application/AppDelegate.swift
  Projects/App/Sources/NotificationService.swift
  Projects/App/Sources/Present/Advertisemets/AdvertisementsControl.swift
  Projects/App/Sources/Present/Auth/SignIn/Model/SignInModel.swift
  Projects/App/Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
  Projects/App/Sources/Present/Auth/SignIn/ViewModel/SignInViewModel.swift
  Projects/App/Sources/Present/Auth/SignUp/Model/SignUpModel.swift
  Projects/App/Sources/Present/Common/Model/PostModel.swift
  Projects/App/Sources/Present/Detail/Model/CommentModel.swift
  Projects/App/Sources/Present/Home/Model/AddPostModel.swift
  Projects/App/Sources/Present/Home/Type/MenuOptionType.swift
  Projects/App/Sources/Present/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Present/Profile/Model/ProfileImageModel.swift
  Projects/App/Sources/Present/Profile/Model/ProfileModel.swift
  Projects/App/Sources/Present/Profile/Type/OptionItemType.swift
  Projects/Shared/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#162 인스타그램 스토리 공유 기능 구현
  Projects/App/ChoiceDebug.entitlements
  Projects/App/Resources/Images.xcassets/InstaBackground.imageset/Contents.json
  Projects/App/Resources/Images.xcassets/InstaBackground.imageset/InstaBackground.png
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/Modal/VC/DetailOptionModalViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/Modal/VC/View/Cell/DetailOptionTableViewCell.swift
  Projects/App/Sources/Present/Detail/ViewController/View/Cell/CommentCell.swift
  Projects/App/Sources/Present/Detail/ViewController/View/DetailPostView.swift
  Projects/App/Sources/Present/Detail/ViewController/View/Modal/Model/OptionData.swift
  Projects/App/Support/Info.plist
  Projects/Shared/Sources/Util/Class/ShareToInstagram.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#165 [Reject] Delete Location Setting
  Projects/App/Support/Info.plist
Labels: 🚑 Hotfix, 🐛 Bugfix

#167 [Refactor] NetworMonitor - 외부 인스턴스 생성 방지
  Projects/App/Sources/Present/Home/ViewController/HomeViewController.swift
  Projects/Core/NetworksMonitor/Sources/NetworkStatus.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#168 Color Setting
  Projects/Core/DesignSystem/Resources/Colors.xcassets/FirstVoteColor.colorset/Contents.json
  Projects/Core/DesignSystem/Resources/Colors.xcassets/SecondVoteColor.colorset/Contents.json
Labels: 3️⃣Priority: Low

#169 불필요한 폴더 & 파일 제거
  Projects/App/Sources/Present/Common/VoteView/View/VoteOptionView.swift
  Projects/App/Sources/Present/Home/ViewModel/Support/Info.plist
Labels: 3️⃣Priority: Low
