Repository SLTDV/Choice-iOS, pull requests merged in 2023-03, with the labels that each got.

#21 PostCell 디자인 변경 적용, retry 문제 해결
  Resources/Colors.xcassets/Gray_Background.colorset/Contents.json
  Resources/Colors.xcassets/Gray_Dark.colorset/Contents.json
  Sources/App/Coordinator/App/AppCoordinator.swift
  Sources/Network/APIConstants.swift
  Sources/Network/JwtRequestInterceptor.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/Cell/PostCell.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#22 게시물 생성 디자인 수정사항 반영
  Resources/Colors.xcassets/Gray_Medium.colorset/Contents.json
  Sources/App/Coordinator/App/AppCoordinator.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#23 게시물 생성 api 변경사항 적용
  Sources/Present/Main/AddPost/Model/AddPostModel.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
  Sources/Present/Main/AddPost/ViewModel/AddPostViewModel.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#24 설정 UI 구현
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 2️⃣Priority: Medium

#25 게시물 생성 - 내용입력 조건 추가
  Sources/Network/JwtRequestInterceptor.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
Labels: 1️⃣Priority: High, ✨ Feature

#26 게시물 생성 시 LoadingView 추가
  Sources/App/Coordinator/App/AppCoordinator.swift
  Sources/Network/APIConstants.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
  Sources/Present/Main/AddPost/ViewModel/AddPostViewModel.swift
  Sources/Util/Class/LoadingIndicator.swift
Labels: 1️⃣Priority: High, ✨ Feature

#28 :recycle: LoadingIndicator warning 해결
  Sources/Util/Class/LoadingIndicator.swift
Labels: 1️⃣Priority: High

#29 변경된 게시물 조회 API 수정
  Sources/Network/APIConstants.swift
  Sources/Network/JwtRequestInterceptor.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Main/Home/Cell/PostCell.swift
  Sources/Present/Main/Home/Model/PostModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 1️⃣Priority: High, ✨ Feature

#27 회원탈퇴/ 로그아웃 기능 구현
  Sources/App/Coordinator/App/AppCoordinator.swift
  Sources/App/Coordinator/Main/Profile/ProfileCoordinator.swift
  Sources/App/Step/ChoiceStep.swift
  Sources/Network/APIConstants.swift
  Sources/Present/Main/Profile/Type/OptionItemType.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 2️⃣Priority: Medium

#30 [Refactoring] APIConstants
  Sources/Network/APIConstants.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring

#31 게시물 정렬 문제 해결 및 투표 기능 구현
  Sources/Network/APIConstants.swift
  Sources/Present/Main/AddPost/ViewModel/AddPostViewModel.swift
  Sources/Present/Main/Home/Cell/PostCell.swift
  Sources/Present/Main/Home/Model/PostModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#32 VotingOption 적용시키기
  Sources/Present/Main/Home/Cell/PostCell.swift
  Sources/Present/Main/Home/View/VoteOptionView.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#34 프로필 이미지 변경 기능
  Sources/Network/APIConstants.swift
  Sources/Present/Common/Cell/PostCell.swift
  Sources/Present/Main/AddPost/ViewModel/AddPostViewModel.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Present/Main/Profile/Model/ProfileImageModel.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 1️⃣Priority: High, ✨ Feature

#35 프로필 이미지 API 적용
  Sources/Present/Main/Profile/Model/ProfileModel.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 1️⃣Priority: High, ✨ Feature

#36 게시물 삭제 기능 구현 / 파일 이동
  Sources/Network/APIConstants.swift
  Sources/Present/Common/Cell/PostCell/Model/PostModel.swift
  Sources/Present/Common/Cell/PostCell/View/PostCell.swift
  Sources/Present/Common/VoteView/View/VoteOptionView.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#37 변경된 디테일 페이지 디자인에 맞춰 로직 수정
  Sources/Present/Common/Cell/PostCell/Model/VoteModel.swift
  Sources/Present/Common/Cell/PostCell/View/PostCell.swift
  Sources/Present/Common/VoteView/View/VoteView.swift
  Sources/Present/Detail/Type/ClassifyVoteButtonType.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#39 투표하지 않았을 때 UI 적용 이슈 해결
  Sources/Network/APIConstants.swift
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Common/Model/PostModel.swift
  Sources/Present/Common/Model/VoteModel.swift
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/Type/ClassifyVoteButtonType.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
Labels: 🚑 Hotfix, 🐛 Bugfix, ✨ Feature

#41 디테일 페이지 UI 수정
  Sources/Network/APIConstants.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#42 홈 페이지에 로고 추가하기
  Resources/Images.xcassets/Contents.json
  Resources/Images.xcassets/HomeLogo.imageset/Contents.json
  Resources/Images.xcassets/HomeLogo.imageset/로고 1.svg
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#43 로그인 페이지 UI 변경
  Resources/Images.xcassets/HomeLogo.imageset/Choice_Logo.svg
  Resources/Images.xcassets/HomeLogo.imageset/Contents.json
  Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#44 프로필 페이지 UI 수정 및 코드 리펙토링
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Common/Type/ViewControllerType.swift
  Sources/Present/Detail/Type/ClassifyVoteButtonType.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Sources/Util/Class/CalculateToVoteCountPercentage.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#45 [Refactoring] PostCell
  Sources/Present/Common/Cell/PostCell/PostCell.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#46 디테일 페이지 API 변경사항 적용
  Sources/Present/Detail/Model/CommentModel.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#48 API 요청 시 header 리펙토링
  Sources/Present/Auth/SignIn/ViewModel/SignInViewModel.swift
  Sources/Present/Auth/SignUp/ViewModel/SignUpViewModel.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/ViewModel/HomeViewModel.swift
  Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#50 댓글달기 로직 수정
  Sources/Network/APIConstants.swift
  Sources/Present/Common/Cell/PostCell/PostCell.swift
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#51 Keyboard 문제 해결
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#52 회원가입 기능구현
  Sources/App/Coordinator/Auth/SignUp/UserProfileInformation/UserProfileInfoCoordinator.swift
  Sources/App/Coordinator/Auth/SignUp/UserSecurityInformation/UserSecurityInfoCoordinator.swift
  Sources/App/Step/ChoiceStep.swift
  Sources/Network/APIConstants.swift
  Sources/Present/Auth/SignUp/Model/SignUpModel.swift
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewModel/UserProfileInfoViewModel.swift
  Sources/Present/Auth/SignUp/UserSecurityInfo/ViewController/UserSecurityInfoViewController.swift
  Sources/Present/Auth/SignUp/UserSecurityInfo/ViewModel/UserSecurityInfoViewModel.swift
  Sources/Present/Auth/SignUp/ViewController/UserProfileInfoViewController.swift
  Sources/Present/Auth/SignUp/ViewModel/UserProfileInfoViewModel.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#53 댓글 - Dynamic Cell 구현
  Project.swift
  Sources/Present/Base/BaseViewModel.swift
  Sources/Present/Detail/Cell/CommentCell.swift
  Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring
