Repository SLTDV/Choice-iOS, pull requests merged in 2023-05, with the labels that each got.

#83 [Refactoring] Tuist Dependency
  .github/workflows/swift.yml
  .tuist-version
  Project.swift
  Sources/Network/JwtRequestInterceptor.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#84 회원가입 로직 변경에 따른 UI / 로직 변경
  Sources/App/Coordinator/Auth/SignIn/SignInCoordinator.swift
  Sources/App/Coordinator/Auth/SignUp/RegistrationPassword/RegistrationPasswordCoordinator.swift
  Sources/App/Coordinator/Auth/SignUp/RegistrationPhoneNumber/RegistrationPhoneNumberCoordinator.swift
  Sources/App/Coordinator/Auth/SignUp/UserProfileInformation/UserProfileInfoCoordinator.swift
  Sources/App/Coordinator/Auth/SignUp/UserSecurityInformation/UserSecurityInfoCoordinator.swift
  Sources/App/Step/ChoiceStep.swift
  Sources/Network/APIConstants.swift
  Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
  Sources/Present/Auth/SignIn/ViewModel/SignInViewModel.swift
  Sources/Present/Auth/SignUp/RegistrationPassword/ViewController/RegistrationPasswordViewController.swift
  Sources/Present/Auth/SignUp/RegistrationPassword/ViewModel/RegistrationPasswordViewModel.swift
  Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
  Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewModel/RegistrationPhoneNumberViewModel.swift
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Sources/Present/Auth/SignUp/UserProfileInfo/ViewModel/UserProfileInfoViewModel.swift
  Sources/Present/Auth/SignUp/UserSecurityInfo/ViewController/UserSecurityInfoViewController.swift
  Sources/Present/Auth/SignUp/UserSecurityInfo/ViewModel/UserSecurityInfoViewModel.swift
  Sources/Util/Class/WarningLabel.swift
  Sources/Util/Extension/UITextfield/UITextfield.swift
Labels: 1️⃣Priority: High

#86 댓글 생성 UI 수정
  .github/workflows/swift.yml
  Projects/App/Sources/Present/Base/BaseVC.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
Labels: 2️⃣Priority: Medium, 🛠️Refactoring

#87 Auth UI 변경
  Projects/App/Sources/Present/Auth/SignIn/ViewController/SignInViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPassword/ViewController/RegistrationPasswordViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
  Projects/App/Sources/Present/Auth/SignUp/UserProfileInfo/ViewController/UserProfileInfoViewController.swift
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewModel/Support/Info.plist
  Projects/Shared/Project.swift
  Projects/Shared/Resources/Colors.xcassets/Contents.json
  Projects/Shared/Resources/Colors.xcassets/FirstVoteColor.colorset/Contents.json
  Projects/Shared/Resources/Colors.xcassets/Gray_Background.colorset/Contents.json
  Projects/Shared/Resources/Colors.xcassets/Gray_Dark.colorset/Contents.json
  Projects/Shared/Resources/Colors.xcassets/Gray_Medium.colorset/Contents.json
  Projects/Shared/Resources/Colors.xcassets/Gray_VoteButton.colorset/Contents.json
  Projects/Shared/Resources/Colors.xcassets/SecondVoteColor.colorset/Contents.json
  Projects/Shared/Sources/Util/Class/BoxTextField/BoxTextField.swift
  Projects/Shared/Sources/Util/Class/BoxTextField/Type/TextFieldType.swift
  Projects/Shared/Sources/Util/Class/UnderLineTextField.swift
  Projects/Shared/Sources/Util/Extension/UITextfield/UITextfield.swift
Labels: 2️⃣Priority: Medium

#88 Fix/comment
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Detail/ViewModel/DetailPostViewModel.swift
  Projects/App/Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Projects/Shared/Sources/Util/Class/CalculateToVoteCountPercentage.swift
  Projects/Shared/Sources/Util/Class/LoadingIndicator.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High

#89 회원탈퇴 시 토큰 삭제
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#90 [Refactoring] 인증요청
  Projects/App/Sources/Present/Auth/SignUp/RegistrationPhoneNum/ViewController/RegistrationPhoneNumberViewController.swift
Labels: 3️⃣Priority: Low

#91 bind 부분 리펙토링
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#92 홈 화면 및 게시물 UI 수정
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Main/AddPost/ViewController/AddPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 3️⃣Priority: Low, 🛠️Refactoring

#93 profile 페이지 alert action message 변경
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 3️⃣Priority: Low

#94 프로필 이미지 contentMode 설정
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 🐛 Bugfix, 3️⃣Priority: Low

#95 BackButton UI 수정
  Projects/App/Sources/Present/Base/BaseVC.swift
Labels: 3️⃣Priority: Low

#99 [피드백 #98] 투표 백분율 로직 수정
  .github/workflows/swift.yml
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/Shared/Sources/Util/Class/CalculateToVoteCountPercentage.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring

#103 [피드백 #100] profile 페이지 layout / UI 수정
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
Labels: 🐛 Bugfix, 3️⃣Priority: Low, 🛠️Refactoring

#102 [피드백 #101] 앱 시작 시 검은화면(Navigation) 이슈 해결
  Projects/App/Sources/App/Application/AppDelegate.swift
  Projects/App/Sources/App/Coordinator/App/AppCoordinator.swift
  Projects/App/Sources/App/Coordinator/App/WhiteViewCoordinator.swift
  Projects/App/Sources/App/Coordinator/Auth/SignIn/SignInCoordinator.swift
  Projects/App/Sources/App/Coordinator/Main/Home/HomeCoordinator.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High, 🛠️Refactoring

#105 [피드백 #104] profile 페이지 layout / UI 수정
  Projects/App/Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 🐛 Bugfix, 1️⃣Priority: High

#108 [피드백 #107] 프로필에서 디테일로 이동로직 추가
  Projects/App/Sources/App/Coordinator/Main/Profile/ProfileCoordinator.swift
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewModel/ProfileViewModel.swift
Labels: 2️⃣Priority: Medium, ✨ Feature
