Repository SLTDV/Choice-iOS, pull requests merged in 2023-07, with the labels that each got.

#142 정렬 Default 값 수정
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
Labels: 2️⃣Priority: Medium

#143 Downsampling 적용 - 메모리 사용량 약 90% 감소
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Common/Model/PostRequest.swift
  Projects/App/Sources/Present/Detail/Cell/CommentCell.swift
  Projects/App/Sources/Present/Detail/View/OptionView.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Projects/Shared/Sources/Util/Class/Downsampling.swift
Labels: 1️⃣Priority: High, 🛠️Refactoring, ✨ Feature

#145 네트워크 상태에 따른 이미지 로딩 속도 문제 해결
  Projects/App/Project.swift
  Projects/App/Sources/App/Application/AppDelegate.swift
  Projects/App/Sources/Present/Common/Cell/PostCell/PostCell.swift
  Projects/App/Sources/Present/Detail/Cell/CommentCell.swift
  Projects/App/Sources/Present/Detail/ViewController/DetailPostViewController.swift
  Projects/App/Sources/Present/Main/Home/ViewController/HomeViewController.swift
  Projects/App/Sources/Present/Main/Profile/ViewController/ProfileViewController.swift
  Projects/Core/NetworksMonitor/Project.swift
  Projects/Core/NetworksMonitor/Resources/Tests.swift
  Projects/Core/NetworksMonitor/Sources/NetworkStatus.swift
  Projects/Core/NetworksMonitor/Tests/Tests.swift
  Projects/Shared/Sources/Util/Class/Downsampling.swift
  Tuist/Dependencies.swift
Labels: 🚑 Hotfix, 🐛 Bugfix
